source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Mention_Example', :exclusive => true do
  pod "Mention", :path => "../"
end

target 'Mention_Tests', :exclusive => true do
  pod "Mention", :path => "../"

  
end
